---
deployment:
  enabled: true
  replicas: 3

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.lungoo.dev`)
    entryPoints:
      - websecure
    middlewares:
      - name: dashboard-ipallowlist
    tls:
      secretName: lungoo-dev-tls

api:
  dashboard: true
  disableDashboardAd: true

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: false

log:
  level: "INFO"

global:
  checkNewVersion: false
  sendAnonymousUsage: false

ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          priority: 10
    proxyProtocol:
      trustedIPs:
        - 100.69.100.2/32
        - fd7a:115c:a1e0::4a01:4779/128
  websecure:
    http:
      tls:
        enabled: true
      middlewares:
        - securityheaders
    proxyProtocol:
      trustedIPs:
        - 100.69.100.2/32
        - fd7a:115c:a1e0::4a01:4779/128

service:
  enabled: true
  annotations:
    metallb.io/loadBalancerIPs: 10.0.255.80,fd87:5445:bcc6:255::80
  spec:
    type: LoadBalancer
    externalTrafficPolicy: Local
    ipFamilies:
      - IPv6
      - IPv4
    ipFamilyPolicy: PreferDualStack

rbac:
  enabled: true

nodeSelector:
  node-role.kubernetes.io/control-plane: "true"
