---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/gchq/cyberchef
    newTag: 11.3.0@sha256:58f68a92fb8e896028f0bb314e6cf5684c9551a84c0b0b2422450ee109b1e883

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
