---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

images:
  - name: ghcr.io/gchq/cyberchef
    newTag: 10.22.1@sha256:3aa4eb2c52c9f9e22bda450cae3187e1de114581f7850d8136c98164837a406c

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
