---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

images:
  - name: ghcr.io/gchq/cyberchef
    newTag: 11.1.0@sha256:76d1ebd550b87d260f96e02d8dce347fb86c6667dbd4ddff8f58430bdf98c423

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
