{{- range .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://10.0.10.101:3000/homelab/homelab.git
    path: kubernetes/apps/{{ .name }}
    targetRevision: feature/migration
  destination:
    namespace: {{ .namespace | default .name }}
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
{{- end }}
