---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - namespace: cnpg-system
    name: cloudnative-pg
    releaseName: cnpg
    repo: https://cloudnative-pg.github.io/charts
    includeCRDs: true
    version: 0.29.0
  - namespace: cnpg-system
    name: plugin-barman-cloud
    releaseName: plugin-barman-cloud
    repo: https://cloudnative-pg.github.io/charts
    includeCRDs: true
    version: 0.7.1

resources:
  - namespace.yaml
  - catalog-standard-trixie.yaml
  - cnpg-storageclass.yaml
  - psql-cluster.yaml
  - ingress.yaml
  - secrets.yaml
  - objectstores.yaml
  - scheduled-backup.yaml
