---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: psql-cluster
  namespace: prod
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 3
  imageName: ghcr.io/lungooo/cloudnative-vectorchord:18

  enableSuperuserAccess: true

  postgresql:
    # TODO: Move to vectorchord extension volume once k3s supports volume extensions
    #   extensions:
    #     - name: vchord
    #       image:
    #         reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.0
    #       dynamic_library_path:
    #         - /usr/lib/postgresql/18/lib/
    #       extension_control_path:
    #         - /usr/share/postgresql/18/
    shared_preload_libraries:
      - "vchord"

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: cnpg-backups

  storage:
    storageClass: longhorn-cnpg-replica-storage
    size: 20Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: psql-cluster
  namespace: testing
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 3

  enableSuperuserAccess: true

  storage:
    storageClass: longhorn-cnpg-replica-storage
    size: 20Gi
