---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: psql-cluster
  namespace: prod
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 3

  enableSuperuserAccess: true

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: cnpg-backups

  storage:
    storageClass: longhorn-cnpg-replica-storage
    size: 20Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: psql-cluster
  namespace: testing
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 3

  enableSuperuserAccess: true

  storage:
    storageClass: longhorn-cnpg-replica-storage
    size: 20Gi
