---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-backups-credentials
  namespace: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: "8e32e0e3-d733-4a14-9f2e-b3f200eef010"
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: "6940c19e-4ee6-40b8-90e1-b3f200ef022c"
