---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/immich-app/immich-server
    newTag: v2.6.2@sha256:1521a1c8c1727ec240e57585db7bf90a3b067066d4847baeb80f353d721f4d5a
  - name: ghcr.io/valkey-io/valkey
    newTag: 9.0.3@sha256:3eeb09785cd61ec8e3be35f8804c8892080f3ca21934d628abc24ee4ed1698f6
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v2.6.2@sha256:2d2d56d12d32b904a86952dd048224d117251d10ed10a4d75279e080e79002b7

resources:
  - configmap.yaml
  - database.yaml
  - deployment-machine-learning.yaml
  - deployment-server.yaml
  - deployment-valkey.yaml
  - ingress.yaml
  - nfs-volumes.yaml
  - pvcs.yaml
  - secrets.yaml
  - serviceaccount.yaml
  - services.yaml
