---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/immich-app/immich-server
    newTag: v2.7.5@sha256:c15bff75068effb03f4355997d03dc7e0fc58720c2b54ad6f7f10d1bc57efaa5
  - name: ghcr.io/valkey-io/valkey
    newTag: 9.0.3@sha256:3b55fbaa0cd93cf0d9d961f405e4dfcc70efe325e2d84da207a0a8e6d8fde4f9
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v2.7.5@sha256:a2501141440f10516d329fdfba2c68082e19eb9ba6016c061ac80d23beadf7f3

resources:
  - configmap.yaml
  - database.yaml
  - deployment-machine-learning.yaml
  - deployment-server.yaml
  - deployment-valkey.yaml
  - ingress.yaml
  - nfs-volumes.yaml
  - pvcs.yaml
  - secrets.yaml
  - serviceaccount.yaml
  - services.yaml
