---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "77db632e-20b9-43ba-8bd7-b3fa000822d3"
