---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-ngx-config
data:
  USERMAP_UID: "1030"
  USERMAP_GID: "100"
  PAPERLESS_URL: "https://paperless.home.lungoo.de"
  PAPERLESS_TIME_ZONE: "Europe/Berlin"
  PAPERLESS_OCR_LANGUAGE: "deu+eng"
  PAPERLESS_REDIS: "redis://paperless-broker:6379"
  PAPERLESS_DBENGINE: "postgresql"
  PAPERLESS_DBHOST: "psql-cluster-rw.prod"
  PAPERLESS_TIKA_ENABLED: "1"
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: "http://paperless-gotenberg:3000"
  PAPERLESS_TIKA_ENDPOINT: "http://paperless-tika:9998"
  PAPERLESS_TRUSTED_PROXIES: "10.43.0.0/16,fd87:5445:bcc6:0200::/112"
  PAPERLESS_ALLAUTH_TRUSTED_PROXY_COUNT: "1"
  PAPERLESS_FILENAME_FORMAT: "{{document_type}}/{{correspondent}}/{{created_year}}/{{created_year}}-{{created_month}}-{{created_day}} - {{title}} - [{{document_type}} {{correspondent}} {{tag_list}} {{asn}}]"
  PAPERLESS_FILENAME_FORMAT_REMOVE_NONE: "True"
  PAPERLESS_DBNAME: "paperless"
  PAPERLESS_DBUSER: "paperless"
  PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
