---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless-ngx-ingress
spec:
  entryPoints:
    - websecure
  ingressClassName: traefik-internal
  routes:
    - match: Host(`paperless.home.lungoo.de`)
      kind: Rule
      services:
        - name: paperless-webserver
          port: 8000
