---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/paperless-ngx/paperless-ngx
    newTag: 2.20.13@sha256:4b05bcd28e6923768000b5d247cbf2c66fd49bdc3f3b05955bd4f6790a638b01
  - name: ghcr.io/valkey-io/valkey
    newTag: 9.0.3@sha256:3b55fbaa0cd93cf0d9d961f405e4dfcc70efe325e2d84da207a0a8e6d8fde4f9
  - name: docker.io/gotenberg/gotenberg
    newTag: 8.29.1@sha256:36c925776fa0db0fd1030408d131fde7ac3453027a559883555155b72adb16a7
  - name: docker.io/apache/tika
    newTag: 3.3.0.0@sha256:2a565f1ea1290bdcb74a7d35957d16a989ed44ef98790dcdcc28121d728fa583

resources:
  - configmap.yaml
  - database.yaml
  - deployment-broker.yaml
  - deployment-gotenberg.yaml
  - deployment-tika.yaml
  - deployment-webserver.yaml
  - ingress.yaml
  - nfs-volumes.yaml
  - pvcs.yaml
  - secrets.yaml
  - serviceaccount.yaml
  - services.yaml
