---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/paperless-ngx/paperless-ngx
    newTag: 2.20.12@sha256:de559198890b6e56bdb696581d80d1e713cecbea15b775a01c08f728a68ffa91
  - name: ghcr.io/valkey-io/valkey
    newTag: 9.0.3@sha256:3eeb09785cd61ec8e3be35f8804c8892080f3ca21934d628abc24ee4ed1698f6
  - name: docker.io/gotenberg/gotenberg
    newTag: 8.28.0@sha256:f172b1ce5ec7516ab9452d33bfe3f198d778d3de39655825aa550f4a33946666
  - name: docker.io/apache/tika
    newTag: 3.2.3.0@sha256:c0154cb95587cde64be74f35ada1a2bd7892219f3f0ac3c9dc6cab34046b3573

resources:
  - configmap.yaml
  - database.yaml
  - deployment-broker.yaml
  - deployment-gotenberg.yaml
  - deployment-tika.yaml
  - deployment-webserver.yaml
  - ingress.yaml
  - nfs-volumes.yaml
  - pvcs.yaml
  - secrets.yaml
  - serviceaccount.yaml
  - services.yaml
