---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    name: paperless-nfs-pvc
  nfs:
    server: 10.0.20.10
    path: /volume1/paperless_testing
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: paperless-nfs-pv
  resources:
    requests:
      storage: 100Gi
