---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        key: "4c518421-1ea9-4f08-8fc8-b3eb00f886e2"
    - secretKey: PAPERLESS_DBPASS
      remoteRef:
        key: "aeaa5246-702e-4c9f-b0c6-b3eb00f8aaa6"
