---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  ingressClassName: traefik-external
  routes:
    - match: Host(`longhorn.home.lungoo.de`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
