---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/jellyfin/jellyfin
    newTag: 12.1@sha256:008ec8024bdaaa6f0a3f0de468e185633eeba9d67c56936e8dbf5ef6b8d6200f

resources:
  - deployment.yaml
  - ingress.yaml
  - nfs-volumes.yaml
  - pvcs.yaml
  - service.yaml
  - serviceaccount.yaml
