---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: psql-cluster-mautrix-whatsapp
  namespace: prod
spec:
  name: mautrix_whatsapp
  owner: mautrix_whatsapp
  cluster:
    name: psql-cluster

