---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: dock.mau.dev/mautrix/whatsapp
    newTag: v26.06@sha256:3ecf348ac3451199fe1e7b894469bd8cf9b2abe58699f3b9a8029172c4356877

configMapGenerator:
  - name: mautrix-wa-config
    files:
      - config.yaml

resources:
  - database.yaml
  - ingress.yaml
  - secrets.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml