---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: dock.mau.dev/mautrix/whatsapp
    newTag: v26.07@sha256:716cb6e6b59b1710bde0b7740e295aa889fef6494a8efcd4ad02ea1965293eaf

configMapGenerator:
  - name: mautrix-wa-config
    files:
      - config.yaml

resources:
  - database.yaml
  - ingress.yaml
  - secrets.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml