---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mautrix-whatsapp-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mautrix-whatsapp-secret
  data:
    - secretKey: MAUTRIX_WA_DATABASE__URI
      remoteRef:
        key: "0035e5af-7353-437d-b329-b43c016536f0"
    - secretKey: MAUTRIX_WA_APPSERVICE__AS_TOKEN
      remoteRef:
        key: "db02b99d-9bf5-4f5c-980d-b43c016570c9"
    - secretKey: MAUTRIX_WA_APPSERVICE__HS_TOKEN
      remoteRef:
        key: "24f60688-86b3-45dc-96ac-b43c0165af71"
    - secretKey: MAUTRIX_WA_PROVISIONING__SHARED_SECRET
      remoteRef:
        key: "68413b3b-def9-417b-a85d-b43c0165d1c5"
    - secretKey: MAUTRIX_WA_PUBLIC_MEDIA__SIGNING_KEY
      remoteRef:
        key: "697a7813-99e0-4832-8ea6-b43c0165f589"
    - secretKey: MAUTRIX_WA_DIRECT_MEDIA__SERVER_KEY
      remoteRef:
        key: "6ccb0385-9143-433a-8e57-b43c016611bb"
    - secretKey: MAUTRIX_WA_DOUBLE_PUPPET__SECRETS__lungoo__dev
      remoteRef:
        key: "88e91b82-e973-4f93-9ffd-b43c01663570"
    - secretKey: MAUTRIX_WA_ENCRYPTION__PICKLE_KEY
      remoteRef:
        key: "6b865c49-3abd-475f-a45e-b43c016652e8"