---
apiVersion: v1
kind: ConfigMap
metadata:
  name: arr-config
data:
  UMASK: "022"
  PUID: "1028"
  PGID: "100"
  TZ: "Europe/Berlin"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sabnzbdvpn-config
data:
  VPN_ENABLED: "yes"
  VPN_PROV: "custom"
  VPN_CLIENT: "wireguard"
  USERSPACE_WIREGUARD: "true"
  ENABLE_PRIVOXY: "yes"
  LAN_NETWORK: "10.0.0.0/16"
  NAME_SERVERS: "84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1"
  DEBUG: "false"
