---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: psql-cluster-prowlarr
  namespace: prod
spec:
  name: prowlarr
  owner: prowlarr
  cluster:
    name: psql-cluster
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: psql-cluster-radarr
  namespace: prod
spec:
  name: radarr
  owner: radarr
  cluster:
    name: psql-cluster
