---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: sabnzbd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sabnzbd
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "opnsense-vpn-vlan",
            "namespace": "kube-system",
            "ips": ["10.0.50.100/24"],
            "default-route": ["10.0.50.1"]
          }]
    spec:
      serviceAccountName: arr
      automountServiceAccountToken: false
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - "84.200.69.80"
          - "9.9.9.9"
          - "1.1.1.1"
      initContainers:
        - name: configure-default-route
          image: public.ecr.aws/docker/library/busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          command:
            - "/bin/sh"
            - "-c"
            - |
              echo "Getting ip address of default gateway"
              ETH0_GW=$(ip route show default dev eth0 | grep "default" | awk '{print $3}')
              echo "ip address of default gateway: $ETH0_GW"

              echo "Adding route for kubernetes services"
              ip route add 10.43.0.0/16 via $ETH0_GW dev eth0
              echo "10.43.0.0/16 -> $ETH0_GW applied successfuly"

              echo "Replacing default route with 10.0.50.1"
              ip route replace default via 10.0.50.1 dev net1
              echo "0.0.0.0/0 -> 10.0.50.1 applied successfuly"
      containers:
        - name: sabnzbd
          image: ghcr.io/linuxserver/sabnzbd
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: arr-config
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
          volumeMounts:
            - name: sabnzbd-config
              mountPath: /config
            - name: data-nfs
              mountPath: /nfs/data/03_media/03_usenet
              subPath: 03_media/03_usenet
      volumes:
        - name: sabnzbd-config
          persistentVolumeClaim:
            claimName: sabnzbd-config-pvc
        - name: data-nfs
          persistentVolumeClaim:
            claimName: data-nfs-pvc
      nodeSelector:
        worker: "true"
