---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/linuxserver/sabnzbd
    newTag: 5.1.1-ls267@sha256:8fb83ceffaca6b9c0cc8d86b1acb525818fe3ce1e5a5ee9e9dd1227a26dce57d
  - name: public.ecr.aws/docker/library/busybox
    newTag: 1.38.0@sha256:1cfa4e2b09e127b9c4ed43578d3f3c18e7d44ea47b9ea98475c0cbe9086525f8
  - name: ghcr.io/linuxserver/prowlarr
    newTag: 2.5.2.5491-ls156@sha256:1295cff29d10b486c0d8324d1559a552140a5932bf8b3d87e398654414f63f92
  - name: ghcr.io/linuxserver/radarr
    newTag: 6.3.0.10514-ls314@sha256:119aaa4a4f7349bcd2a136c5373a0d7925b5479915c7dfe0c0ad352db2a6d438
  - name: ghcr.io/linuxserver/sonarr
    newTag: 4.0.19.2979-ls322@sha256:c19aa4ecdf03d73e1d5c901da33744cb7eb4d921f89bafed1ca264601d7fa224

resources:
  - configmaps.yaml
  - databases.yaml
  - deployment-prowlarr.yaml
  - deployment-radarr.yaml
  - deployment-sabnzbd.yaml
  - deployment-sonarr.yaml
  - ingress.yaml
  - nfs-volumes.yaml
  - pvcs.yaml
  - secrets.yaml
  - serviceaccount.yaml
  - services.yaml
