---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/linuxserver/sabnzbd
    newTag: 5.1.3-ls272@sha256:7f173ced3541b46c57c4eb6854765243095c8c8a7563a878044fa0ccfb1f4004
  - name: public.ecr.aws/docker/library/busybox
    newTag: 1.38.0@sha256:f97baa533a26513c453a362be331a43eb60214302f449c16571b23cea141dce4
  - name: ghcr.io/linuxserver/prowlarr
    newTag: 2.6.5.5623-ls162@sha256:f2b26429893d4c4cb71941b7ee50b1bdecd9d5f9f9e02d5410615e9f4f7c8d95
  - name: ghcr.io/linuxserver/radarr
    newTag: 6.4.4.10685-ls318@sha256:adb6c09d6b729ea5e642c99cea35af72702ef476bf4763f153299ac5db9f0b4f
  - name: ghcr.io/linuxserver/sonarr
    newTag: 4.0.20.3014-ls325@sha256:a5c1a5fecbef946927ab90ad68df319ac5fe644057e5fc18cd993f01ac07b2b2

resources:
  - configmaps.yaml
  - databases.yaml
  - deployment-prowlarr.yaml
  - deployment-radarr.yaml
  - deployment-sabnzbd.yaml
  - deployment-sonarr.yaml
  - ingress.yaml
  - nfs-volumes.yaml
  - pvcs.yaml
  - secrets.yaml
  - serviceaccount.yaml
  - services.yaml
