---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: PROWLARR__POSTGRES__PASSWORD
      remoteRef:
        key: "44715704-2069-4d7e-ae67-b47700909bf4"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: RADARR__POSTGRES__PASSWORD
      remoteRef:
        key: "07522cac-1c5d-4171-ad52-b47800de1fb0"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: SONARR__POSTGRES__PASSWORD
      remoteRef:
        key: "d2b48da1-67ae-4d23-bf1f-b47801130692"
