---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: PROWLARR__POSTGRES__PASSWORD
      remoteRef:
        key: "44715704-2069-4d7e-ae67-b47700909bf4"
