---
deployment:
  enabled: true
  replicas: 3

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.home.lungoo.de`)
    entryPoints:
      - websecure
    tls:
      secretName: home-lungoo-de-tls

api:
  dashboard: true
  disableDashboardAd: true

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-internal
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: false

log:
  level: "INFO"

global:
  checkNewVersion: false
  sendAnonymousUsage: false

additionalArguments:
  - "--entrypoints.pg.address=:5432/tcp"

ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          priority: 10
  websecure:
    http:
      tls:
        enabled: true
      middlewares:
        - securityheaders
    transport:
      respondingTimeouts:
        readTimeout: 300s
        idleTimeout: 300s
  pg:
    port: 5432
    expose:
      default: true
    exposedPort: 5432
    protocol: TCP

service:
  enabled: true
  annotations:
    metallb.io/loadBalancerIPs: 10.0.10.180,fd87:5445:bcc6:10::b4
  spec:
    type: LoadBalancer
    externalTrafficPolicy: Local
    ipFamilies:
      - IPv6
      - IPv4
    ipFamilyPolicy: PreferDualStack

rbac:
  enabled: true

nodeSelector:
  node-role.kubernetes.io/control-plane: "true"
