---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: dock.mau.dev/mautrix/telegram
    newTag: v26.07@sha256:5a8c0e02f6333c7610ca429a2d643f15ea02fcf52e95647af6e76d5d5cbc78f3

configMapGenerator:
  - name: mautrix-tg-config
    files:
      - config.yaml

resources:
  - database.yaml
  - ingress.yaml
  - secrets.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml