---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: dock.mau.dev/mautrix/telegram
    newTag: v26.06@sha256:8c6c559446f049c1f3c4cbc4b284aed14c27aefde9b88a785d262633bdafe510

configMapGenerator:
  - name: mautrix-tg-config
    files:
      - config.yaml

resources:
  - database.yaml
  - ingress.yaml
  - secrets.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml