---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: dock.mau.dev/mautrix/telegram
    newTag: v26.09@sha256:03e79bcf076da566a9984b0bc06151acbf71e3df9cd2e291142713ad9ebff980

configMapGenerator:
  - name: mautrix-tg-config
    files:
      - config.yaml

resources:
  - database.yaml
  - ingress.yaml
  - secrets.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml