---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mautrix-telegram-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mautrix-telegram-secret
  data:
    - secretKey: MAUTRIX_TG_NETWORK__API_ID
      remoteRef:
        key: "346cbfee-045b-49b0-8c87-b43d00b6a264"
    - secretKey: MAUTRIX_TG_NETWORK__API_HASH
      remoteRef:
        key: "1d2e73cb-f40f-4cf4-bcac-b43d00b6bcf8"
    - secretKey: MAUTRIX_TG_DATABASE__URI
      remoteRef:
        key: "fb40cec2-e2a9-4910-baac-b43d00b71b45"
    - secretKey: MAUTRIX_TG_APPSERVICE__AS_TOKEN
      remoteRef:
        key: "c37ae454-c0f0-4208-bede-b43d00b72e19"
    - secretKey: MAUTRIX_TG_APPSERVICE__HS_TOKEN
      remoteRef:
        key: "3b250eaa-b85e-4ca2-81d1-b43d00b74017"
    - secretKey: MAUTRIX_TG_PROVISIONING__SHARED_SECRET
      remoteRef:
        key: "1a0ed4e9-0c14-4859-a334-b43d00b75c34"
    - secretKey: MAUTRIX_TG_PUBLIC_MEDIA__SIGNING_KEY
      remoteRef:
        key: "624fae63-fade-4123-8e86-b43d00b771d4"
    - secretKey: MAUTRIX_TG_DIRECT_MEDIA__SERVER_KEY
      remoteRef:
        key: "842a77c6-a775-49af-b06e-b43d00b78899"
    - secretKey: MAUTRIX_TG_DOUBLE_PUPPET__SECRETS__lungoo__dev
      remoteRef:
        key: "b61c6fcf-441b-42ec-b09a-b43d00b7a2e3"
    - secretKey: MAUTRIX_TG_ENCRYPTION__PICKLE_KEY
      remoteRef:
        key: "f0a1ce66-7c4f-4187-ba74-b43d00b7b581"