---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: dock.mau.dev/mautrix/signal
    newTag: v26.06@sha256:0adf4fc6ba9d7ae95a0904f8432cde637093948a615612058934a7a484221390

configMapGenerator:
  - name: mautrix-signal-config
    files:
      - config.yaml

resources:
  - database.yaml
  - ingress.yaml
  - secrets.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml