---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: dock.mau.dev/mautrix/signal
    newTag: v26.05@sha256:24ac347858e4c522bd1292e8cae344d736840036760944b9abc0d94f1561d41a

configMapGenerator:
  - name: mautrix-signal-config
    files:
      - config.yaml

resources:
  - database.yaml
  - ingress.yaml
  - secrets.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml