---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mautrix-signal-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mautrix-signal-secret
  data:
    - secretKey: MAUTRIX_SIGNAL_DATABASE__URI
      remoteRef:
        key: "3934bbe8-cfbd-4ee7-8b17-b43d00d3af92"
    - secretKey: MAUTRIX_SIGNAL_APPSERVICE__AS_TOKEN
      remoteRef:
        key: "58396a46-f7f8-468c-98ec-b43d00d3d28e"
    - secretKey: MAUTRIX_SIGNAL_APPSERVICE__HS_TOKEN
      remoteRef:
        key: "88ccc906-9d3e-4024-8f24-b43d00d3f271"
    - secretKey: MAUTRIX_SIGNAL_PROVISIONING__SHARED_SECRET
      remoteRef:
        key: "72cda4ee-a901-4272-8a03-b43d00d41869"
    - secretKey: MAUTRIX_SIGNAL_PUBLIC_MEDIA__SIGNING_KEY
      remoteRef:
        key: "aee3f9ac-f459-47e7-9468-b43d00d43f55"
    - secretKey: MAUTRIX_SIGNAL_DIRECT_MEDIA__SERVER_KEY
      remoteRef:
        key: "df094f76-a0f7-44e0-bacc-b43d00d45bc9"
    - secretKey: MAUTRIX_SIGNAL_DOUBLE_PUPPET__SECRETS__lungoo__dev
      remoteRef:
        key: "e874a1ae-b2a3-4232-b7ca-b43d00d47260"
    - secretKey: MAUTRIX_SIGNAL_ENCRYPTION__PICKLE_KEY
      remoteRef:
        key: "7713b2ba-92ed-40b0-b994-b43d00d48e5a"