---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

images:
  - name: ghcr.io/actualbudget/actual
    newTag: 26.4.0@sha256:b0e732e2c41b3dc468a71548e88ef76d3f0c157fc43d15fa05d14ec1c5747e1e

resources:
  - deployment.yaml
  - ingress.yaml
  - pvc.yaml
  - service.yaml
