---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

images:
  - name: ghcr.io/actualbudget/actual
    newTag: 26.2.1@sha256:ea21a0b6243797d35ef6c4a8713c87efaba8fec3b3663220fa3af61f352fba5e

resources:
  - deployment.yaml
  - ingress.yaml
  - pvc.yaml
  - service.yaml
