---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

images:
  - name: ghcr.io/actualbudget/actual
    newTag: 26.3.0@sha256:eb8bc26f53025e07e464594c12d77c52c4b95840c8dadd9b95c4f0c4660f8ad2

resources:
  - deployment.yaml
  - ingress.yaml
  - pvc.yaml
  - service.yaml
