---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zerossl-eab-secret
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: eab-key
      remoteRef:
        key: "0bb6bbca-a94f-43b3-a9dd-b3f900959a5d"
