---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/lldap/lldap
    newTag: v0.6.3@sha256:2a8454b668c1aba7157e832eab0e242e1e7eb5fb7591d7e7774ba05286511ca8

resources:
  - configmap.yaml
  - database.yaml
  - deployment.yaml
  - ingress.yaml
  - secrets.yaml
  - serviceaccount.yaml
  - services.yaml
