---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lldap-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: LLDAP_JWT_SECRET
      remoteRef:
        key: "361316ae-f1ff-4c03-b5a9-b49301452f4c"
    - secretKey: LLDAP_KEY_SEED
      remoteRef:
        key: "64316be1-af22-418d-b2e5-b49301453d65"
    - secretKey: LLDAP_LDAP_USER_DN
      remoteRef:
        key: "68269f83-7378-491b-92cd-b49301455a03"
    - secretKey: LLDAP_LDAP_USER_EMAIL
      remoteRef:
        key: "8fb69aaf-eee3-47f9-a4bf-b493014576a4"
    - secretKey: LLDAP_LDAP_USER_PASS
      remoteRef:
        key: "2c6b5fcb-e663-471a-8d9e-b49301458dad"
    - secretKey: LLDAP_DATABASE_URL
      remoteRef:
        key: "8c184b9c-b27d-432d-afd8-b4930145c88b"
    - secretKey: LLDAP_SMTP_OPTIONS__SERVER
      remoteRef:
        key: "60e86ea9-3786-4115-9729-b49301461c2c"
    - secretKey: LLDAP_SMTP_OPTIONS__USER
      remoteRef:
        key: "1d48e7aa-7736-4184-8500-b4930146877d"
    - secretKey: LLDAP_SMTP_OPTIONS__PASSWORD
      remoteRef:
        key: "4b94337c-6c4b-4b26-b4f7-b4930146cd28"
