---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-secret
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: oidc.auth0.clientSecret
      remoteRef:
        key: "65d6595a-b9fa-4e19-a35c-b49600a32223"
