---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seerr-config
data:
  LOG_LEVE: "debug"
  DB_TYPE: "postgres"
  DB_NAME: "seerr"
  DB_HOST: "psql-cluster-rw"
  DB_USER: "seerr"
  TZ: "Europe/Berlin"
