---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: DB_PASS
      remoteRef:
        key: "e2ad7edf-ae8c-4188-b05f-b47501584c94"
