---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - adguardhome.yaml
  - forgejo.yaml
  - garage.yaml
  - home-assistant.yaml
  - pbs.yaml
  - pve.yaml
  - synology.yaml
