---
core_components:
  - name: argocd
  - name: cert-manager
  - name: crowdsec
  - name: external-secrets
  - name: github-arc-controller
    namespace: arc-system
  - name: github-arc-scale-set
    namespace: arc-runners
  - name: longhorn
    namespace: longhorn-system
  - name: metallb
    namespace: metallb-system
  - name: multus-cni
    namespace: kube-system
  # - name: reflector
  - name: reloader
  - name: traefik-internal
    namespace: traefik-internal
    path: traefik/internal
  - name: traefik-external
    namespace: traefik-external
    path: traefik/external
