---
- op: add
  path: /spec/template/spec/containers/0/envFrom
  value:
    - secretRef:
        name: authelia-env-secret
- op: add
  path: /spec/template/spec/volumes/2/secret/items/-
  value:
    key: identity_providers.oidc.jwk.RS256.pem
    path: identity_providers.oidc.jwk.RS256.pem
