---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/valkey-io/valkey
    newTag: 9.1.1@sha256:64e361b630ecf18dff7ca4df6a88e6eafc193687eb48cff2c7e0a293ab67d29a

helmCharts:
  - namespace: authelia
    name: authelia
    releaseName: authelia
    repo: https://charts.authelia.com
    includeCRDs: true
    valuesFile: values.yaml
    version: 0.11.20

resources:
  - database.yaml
  - deployment-valkey.yaml
  - ingress.yaml
  - middleware.yaml
  - pvc.yaml
  - secrets.yaml
  - service.yaml
  - serviceaccount.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: authelia
    path: authelia-deploy-patch.yaml
