---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/valkey-io/valkey
    newTag: 9.1.1@sha256:3acc0687f2a2e1091fae6450d7842dd658c941338cf0a873ddd9e14b9e4ea4dd

helmCharts:
  - namespace: authelia
    name: authelia
    releaseName: authelia
    repo: https://charts.authelia.com
    includeCRDs: true
    valuesFile: values.yaml
    version: 0.11.6

resources:
  - database.yaml
  - deployment-valkey.yaml
  - ingress.yaml
  - middleware.yaml
  - pvc.yaml
  - secrets.yaml
  - service.yaml
  - serviceaccount.yaml

patches:
  - path: authelia-deploy-patch.yaml
