---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-env-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: AUTHELIA_NOTIFIER_SMTP_ADDRESS
      remoteRef:
        key: "47f4147d-5485-4d20-b36a-b49400c20995"
    - secretKey: AUTHELIA_NOTIFIER_SMTP_USERNAME
      remoteRef:
        key: "bea34bf6-4e6b-4e8b-8c7a-b49400c23059"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: authentication.ldap.password.txt
      remoteRef:
        key: "52ce7963-d4f1-4005-a1e6-b49400c09ece"
    - secretKey: identity_validation.reset_password.jwt.hmac.key
      remoteRef:
        key: "301af79c-a422-4ab1-ac32-b49400c0f8a3"
    - secretKey: notifier.smtp.password.txt
      remoteRef:
        key: "0ee55722-c8df-4ff3-8a12-b49400c2d868"
    - secretKey: session.encryption.key
      remoteRef:
        key: "1174d442-d92b-40d4-b4fe-b49400c17a67"
    - secretKey: storage.encryption.key
      remoteRef:
        key: "a1e750ec-d69c-4d32-9c5b-b49400c1a186"
    - secretKey: storage.postgres.password.txt
      remoteRef:
        key: "798236a2-d420-4d15-b849-b49400c334a4"
    - secretKey: identity_providers.oidc.hmac.key
      remoteRef:
        key: "2e92909c-4f1d-4e3a-a5bb-b4950113a498"
    - secretKey: identity_providers.oidc.jwk.RS256.pem
      remoteRef:
        key: "caec549c-0e7e-4e15-836f-b4950113e93c"
    - secretKey: identity_providers.oidc.actual-budget.client_secret
      remoteRef:
        key: "14d12296-d76e-4c82-bf4e-b495011d44b6"
    - secretKey: identity_providers.oidc.immich.client_secret
      remoteRef:
        key: "5daa55d8-a2d5-41a0-b8dc-b49501270ba4"
    - secretKey: identity_providers.oidc.paperless.client_secret
      remoteRef:
        key: "3ff74709-2e52-4d3f-9350-b495012e42c2"
