---
rbac:
  enabled: true

ingress:
  enabled: false

pod:
  kind: Deployment
  labels:
    network/allow-external: "true"
  selectors:
    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"

configMap:
  log:
    format: "json"
  theme: "auto"
  totp:
    issuer: "Authelia <lungoo.dev>"
  webauthn:
    enable_passkey_login: true
    display_name: "Authelia <lungoo.dev>"
  authentication_backend:
    ldap:
      enabled: true
      implementation: "lldap"
      address: "ldap://lldap.lldap:3890"
      base_dn: "DC=lungoo,dc=dev"
      user: "UID=authelia,OU=people,DC=lungoo,DC=dev"
  access_control:
    default_policy: deny
    rules:
      - domain:
          - "*.home.lungoo.de"
          - "home.lungoo.de"
          - "*.lungoo.dev"
          - "lungoo.dev"
        subject:
          - "group:administrator"
        policy: two_factor
      - domain:
          - "whoami.home.lungoo.de"
          - "whoami.lungoo.dev"
        subject:
          - "group:users"
        policy: two_factor
  session:
    cookies:
      - subdomain: "auth"
        domain: "lungoo.dev"
        same_site: "lax"
        inactivity: "30m"
        expiration: "1d"
      - subdomain: "auth"
        domain: "home.lungoo.de"
        same_site: "lax"
        inactivity: "30m"
        expiration: "1d"
    redis:
      enabled: true
      deploy: false
      host: "authelia-valkey"
      password:
        disabled: true
  storage:
    postgres:
      enabled: true
      deploy: false
      address: tcp://psql-cluster-rw.prod:5432
  notifier:
    smtp:
      enabled: true
      sender: "Authelia <authelia@lungoo.dev>"
  identity_providers:
    oidc:
      enabled: true
      jwks:
        - key:
            path: "/secrets/internal/identity_providers.oidc.jwk.RS256.pem"
      clients:
        - client_id: "yWZ3V1fyYHVww8sYWVXrxFud2jLxkmWslHtXCxMT4oQO231HQ7ldUQANKphi6Sv3"
          client_name: "Actual Budget"
          client_secret:
            path: "/secrets/internal/identity_providers.oidc.actual-budget.client_secret"
          public: false
          authorization_policy: "two_factor"
          require_pkce: false
          pkce_challenge_method: ""
          redirect_uris:
            - "https://actual-budget.home.lungoo.de/openid/callback"
          scopes:
            - "openid"
            - "profile"
            - "groups"
            - "email"
          response_types:
            - "code"
          grant_types:
            - "authorization_code"
          access_token_signed_response_alg: "none"
          userinfo_signed_response_alg: "none"
          token_endpoint_auth_method: "client_secret_basic"
        - client_id: "QSPNIra4FNEU9x64dmFlptgvsGF99jvare7Dz9DyHZWwJ5saxxjt7kEroHIZpfOv"
          client_name: "Immich"
          client_secret:
            path: "/secrets/internal/identity_providers.oidc.immich.client_secret"
          public: false
          authorization_policy: "two_factor"
          require_pkce: false
          pkce_challenge_method: ""
          redirect_uris:
            - "https://immich.home.lungoo.de/auth/login"
            - "https://immich.home.lungoo.de/user-settings"
            - "app.immich:///oauth-callback"
          scopes:
            - "openid"
            - "profile"
            - "email"
          response_types:
            - "code"
          grant_types:
            - "authorization_code"
          access_token_signed_response_alg: "none"
          userinfo_signed_response_alg: "none"
          token_endpoint_auth_method: "client_secret_post"

secret:
  existingSecret: "authelia-secret"
