---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/jackjpowell/uc-intg-manager
    newTag: v3.2.0@sha256:7e37eaa0a257da6f3ed4b1d0ec778435b3f98410746756d41c5dbfe91670c996

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - pvc.yaml
