---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/jackjpowell/uc-intg-manager
    newTag: v2.0.6@sha256:653bf310a74b7b40644eb3bb5450ab02f7436f46af2e33e94cae32d26edeffab

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - pvc.yaml
