---
apiVersion: v1
kind: Service
metadata:
  name: uc-intg-manager-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: uc-intg-manager
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: api
    - port: 9999
      targetPort: 9999
      protocol: TCP
      name: http
