---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-secret
  namespace: crowdsec
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: ENROLL_KEY
      remoteRef:
        key: "375e115d-3032-420f-9cfa-b49300e29bde"
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "154fbe28-d566-47f7-ab0a-b49300ece4a2"
    - secretKey: BOUNCER_KEY_traefik
      remoteRef:
        key: "2edee0e8-5337-443b-b85f-b49300e4bd7b"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: traefik-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: BOUNCER_KEY_traefik
      remoteRef:
        key: "2edee0e8-5337-443b-b85f-b49300e4bd7b"
