---
name: Kubectl validate
on:
  pull_request:
    branches:
      - main
    paths:
      - "kubernetes/**"

permissions:
  contents: read
  pull-requests: read

jobs:
  changed-apps:
    runs-on: arc-runner-set
    name: Find changed apps
    container:
      image: alpine/k8s:1.36.2@sha256:44ef4942e171939b9c665a4a84beb80e2dcdb9a24330d4651cfdfd2e9deecc47
    outputs:
      apps_matrix: ${{ steps.changed-apps.outputs.apps_matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          matrix: true
          dir_names: true

      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

      - name: Filter apps matrix
        id: changed-apps
        run: |
          CHANGED_FILES='${{ steps.changed-files.outputs.all_changed_files }}'
          APPS=$(echo $CHANGED_FILES | jq -r '.[] | select(startswith("kubernetes"))' | jq -R . | jq -sc .)
          echo "Filtered matrix: $APPS"
          echo apps_matrix=$APPS >> $GITHUB_OUTPUT
        shell: bash

  validation:
    runs-on: arc-runner-set
    name: Validate ${{ matrix.app }}
    needs: changed-apps
    container:
      image: alpine/k8s:1.36.2@sha256:44ef4942e171939b9c665a4a84beb80e2dcdb9a24330d4651cfdfd2e9deecc47
    strategy:
      matrix:
        app: ${{ fromJSON(needs.changed-apps.outputs.apps_matrix) }}
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Verify Manifests
        run: |
          if [ -f "${{ matrix.app }}/Chart.yaml" ]; then
            echo "Chart.yaml found. Running helm template..."
            helm template validate ${{ matrix.app }} | kubeconform -strict -summary \
              -schema-location default \
              -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'
          elif [ -f "${{ matrix.app }}/kustomization.yaml" ] || [ -f "${{ matrix.app }}/kustomization.yml" ]; then
            echo "Kustomization found. Running kustomize build..."
            kustomize build --enable-helm ${{ matrix.app }} | kubeconform -strict -summary \
              -schema-location default \
              -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'
          else
            echo "Neither Chart.yaml nor kustomization.yaml found in ${{ matrix.app }}. Skipping."
            touch ${{ matrix.app }}/bundle.yaml
          fi

  validation-result:
    runs-on: arc-runner-set
    name: Validation result
    needs: validation
    container:
      image: alpine/k8s:1.36.2@sha256:44ef4942e171939b9c665a4a84beb80e2dcdb9a24330d4651cfdfd2e9deecc47
    steps:
      - name: Set status based on build
        run: |
          if [ "${{ needs.validation.result }}" == "success" ]; then
            echo "Validation succeeded."
          else
            echo "Validation failed."
            exit 1
          fi
