---
name: Workflow lint
on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"

permissions:
  contents: read
  pull-requests: read

jobs:
  changed-workflows:
    runs-on: arc-runner-set
    name: Find changed workflow files
    container:
      image: alpine/k8s:1.36.2@sha256:44ef4942e171939b9c665a4a84beb80e2dcdb9a24330d4651cfdfd2e9deecc47
    outputs:
      workflows_matrix: ${{ steps.changed-workflows.outputs.workflows_matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          matrix: true
          dir_names: false

      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

      - name: Filter workflows matrix
        id: changed-workflows
        run: |
          CHANGED_FILES='${{ steps.changed-files.outputs.all_changed_files }}'
          WORKFLOWS=$(echo $CHANGED_FILES | jq -r '.[] | select(startswith(".github"))' | jq -R . | jq -sc .)
          echo "Filtered matrix: $WORKFLOWS"
          echo workflows_matrix=$WORKFLOWS >> $GITHUB_OUTPUT
        shell: bash

  validation:
    runs-on: arc-runner-set
    name: Validate ${{ matrix.workflow }}
    needs: changed-workflows
    container:
      image: pipelinecomponents/yamllint:0.35.13@sha256:5ab5eb7da0ed5e606b07c1723fc8b275e925189f70ac259b26b7329cb5f8f44d
    strategy:
      matrix:
        workflow: ${{ fromJSON(needs.changed-workflows.outputs.workflows_matrix) }}
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: yamllint
        run: |
          yamllint -c _yamllint.yaml ${{ matrix.workflow }}

  validation-result:
    runs-on: arc-runner-set
    name: Validation result
    needs: validation
    container:
      image: alpine/k8s:1.36.2@sha256:44ef4942e171939b9c665a4a84beb80e2dcdb9a24330d4651cfdfd2e9deecc47
    steps:
      - name: Set status based on build
        run: |
          if [ "${{ needs.validation.result }}" == "success" ]; then
            echo "Validation succeeded."
          else
            echo "Validation failed."
            exit 1
          fi
